export const start = new Date(2022, 12, 5, 9, 45);

const time = new Date(2022, 12, 5, 9, 45);

export const sessionData = [
    {
        id:1,
        title:"Smoke Ceremony",
        start: [
            2022,
            12,
            5,
            9,
            45,
        ],
        end: [
            2022,
            12,
            5,
            10,
            15,
        ],
        Desc:"Test Description to Make sure this is working.",
        IsMulti:false,
    },
    {
        id:2,
        title:"Morning Tea",
        start: [
            2022,
            12,
            5,
            10,
            15,
        ],
        end: [
            2022,
            12,
            5,
            10,
            45,
        ],
        Desc:"Test Description to Make sure this is working.",
        IsMulti:false,
    },
    {
        id:3,
        title:"Welcome to Country",
        start: [
            2022,
            12,
            5,
            10,
            45,
        ],
        end: [
            2022,
            12,
            5,
            12,
            0,
        ],
        Desc:"Welcome to Country (Bell) + Opening Reading (Collis), Talk (Bronham) and Performance (TBA)",
        IsMulti:false,
    },
    {
        id:4,
        title:"Lunch",
        start: [
            2022,
            12,
            5,
            12,
            0,
        ],
        end: [
            2022,
            12,
            5,
            13,
            0,
        ],
        Desc:"Test Description to Make sure this is working.",
        IsMulti:false,
    },
    {
        id:5,
        title:"Session 1",
        start: [
            2022,
            12,
            5,
            13,
            0,
        ],
        end: [
            2022,
            12,
            5,
            14,
            30,
        ],
        Desc:"Test Description to Make sure this is working.",
        IsMulti:true,
    },
    {
        id:6,
        title:"Afternoon Tea",
        start: [
            2022,
            12,
            5,
            14,
            30,
        ],
        end: [
            2022,
            12,
            5,
            15,
            0,
        ],
        Desc:"Test Description to Make sure this is working.",
        IsMulti:false,
    },
    {
        id:7,
        title:"Session 2",
        start: [
            2022,
            12,
            5,
            15,
            0,
        ],
        end: [
            2022,
            12,
            5,
            16,
            30,
        ],
        Desc:"Test Description to Make sure this is working.",
        IsMulti:true,
    },
    {
        id:8,
        title:"Drinks",
        start: [
            2022,
            12,
            5,
            16,
            30,
        ],
        end: [
            2022,
            12,
            5,
            17,
            0,
        ],
        Desc:"Test Description to Make sure this is working.",
        IsMulti:false,
    },
    {
        id:9,
        title:"Keynote Poetry Readings",
        start: [
            2022,
            12,
            5,
            17,
            0,
        ],
        end: [
            2022,
            12,
            5,
            18,
            30,
        ],
        Desc:" (Van/ Kalytiak-Davis/ Sakr)",
        IsMulti:false,
    },
    {
        id:10,
        title:"Keynote Lecture by Heather Clark",
        start: [
            2022,
            12,
            6,
            9,
            30,
        ],
        end: [
            2022,
            12,
            6,
            11,
            0,
        ],
        Desc:"Test Description to Make sure this is working.",
        IsMulti:false,
    },
    {
        id:11,
        title:"Morning Tea",
        start: [
            2022,
            12,
            6,
            11,
            0,
        ],
        end: [
            2022,
            12,
            6,
            11,
            30,
        ],
        Desc:"Test Description to Make sure this is working.",
        IsMulti:false,
    },
    {
        id:12,
        title:"Session 3",
        start: [
            2022,
            12,
            6,
            11,
            30,
        ],
        end: [
            2022,
            12,
            6,
            13,
            0,
        ],
        Desc:"Test Description to Make sure this is working.",
        IsMulti:true,
    },
    {
        id:13,
        title:"Lunch",
        start: [
            2022,
            12,
            6,
            13,
            0,
        ],
        end: [
            2022,
            12,
            6,
            14,
            30,
        ],
        Desc:"Lunch + Open Sessions",
        IsMulti:false,
    },
    {
        id:14,
        title:"Session 4",
        start: [
            2022,
            12,
            6,
            14,
            30,
        ],
        end: [
            2022,
            12,
            6,
            16,
            0,
        ],
        Desc:"Test Description to Make sure this is working.",
        IsMulti:true,
    },
    {
        id:15,
        title:"Afternoon Tea",
        start: [
            2022,
            12,
            6,
            16,
            0,
        ],
        end: [
            2022,
            12,
            6,
            16,
            30,
        ],
        Desc:"Test Description to Make sure this is working.",
        IsMulti:false,
    },
    {
        id:16,
        title:"Poetry and Film Event",
        start: [
            2022,
            12,
            6,
            16,
            30,
        ],
        end: [
            2022,
            12,
            6,
            18,
            0,
        ],
        Desc:" Magic Lantern Performance",
        IsMulti:false,
    },
    {
        id:17,
        title:"Bus to Dinner",
        start: [
            2022,
            12,
            6,
            18,
            30,
        ],
        end: [
            2022,
            12,
            6,
            19,
            0,
        ],
        Desc:"Optional",
        IsMulti:false,
    },
    {
        id:18,
        title:"Conference Dinner",
        start: [
            2022,
            12,
            6,
            19,
            0,
        ],
        end: [
            2022,
            12,
            6,
            20,
            30,
        ],
        Desc:"Optional",
        IsMulti:false,
    },
    {
        id:19,
        title:"Keynote Panel",
        start: [
            2022,
            12,
            7,
            9,
            0,
        ],
        end: [
            2022,
            12,
            7,
            10,
            30,
        ],
        Desc:"Poetry and Ordinary Language Philosophy (Clements / McArthur/ Musgrave/ Van)",
        IsMulti:false,
    },
    {
        id:20,
        title:"Morning Tea",
        start: [
            2022,
            12,
            7,
            10,
            30,
        ],
        end: [
            2022,
            12,
            7,
            11,
            0,
        ],
        Desc:"Test Description to Make sure this is working.",
        IsMulti:false,
    },
    {
        id:21,
        title:"Session 5",
        start: [
            2022,
            12,
            7,
            11,
            0,
        ],
        end: [
            2022,
            12,
            7,
            12,
            30,
        ],
        Desc:"Test Description to Make sure this is working.",
        IsMulti:true,
    },
    {
        id:22,
        title:"Lunch",
        start: [
            2022,
            12,
            7,
            12,
            30,
        ],
        end: [
            2022,
            12,
            7,
            13,
            30,
        ],
        Desc:"Test Description to Make sure this is working.",
        IsMulti:false,
    },
    {
        id:23,
        title:"Session 6",
        start: [
            2022,
            12,
            7,
            13,
            30,
        ],
        end: [
            2022,
            12,
            7,
            15,
            0,
        ],
        Desc:"Test Description to Make sure this is working.",
        IsMulti:true,
    },
    {
        id:24,
        title:"Afternoon Tea",
        start: [
            2022,
            12,
            7,
            15,
            0,
        ],
        end: [
            2022,
            12,
            7,
            15,
            30,
        ],
        Desc:"Test Description to Make sure this is working.",
        IsMulti:false,
    },
    {
        id:25,
        title:"Session 7",
        start: [
            2022,
            12,
            7,
            15,
            30,
        ],
        end: [
            2022,
            12,
            7,
            17,
            0,
        ],
        Desc:"Test Description to Make sure this is working.",
        IsMulti:true,
    },
    {
        id:26,
        title:"Finnegans Wake 'Funferal'",
        start: [
            2022,
            12,
            7,
            19,
            30,
        ],
        end: [
            2022,
            12,
            7,
            21,
            30,
        ],
        Desc:"Test Description to Make sure this is working.",
        IsMulti:false,
    },
    
    
];
  
// export sessionData;

export const timeValueDisplay = [
        "8am",
        "9am",
        "10am",
        "11am",
        "12pm",
        "1pm",
        "2pm",
        "3pm",
        "4pm",
        "5pm",
        "6pm",
        "7pm",
        "8pm",
        "9pm"
];

export const timeAreaValue = [
    0,
    4,
    8,
    12,
    16,
    20,
    23,
    27,
    31,
    35,
    39,
    43,
    47,
    51,
    54,
];



export const timeGridData = 
    {
        "08:00":0,
        "08:15":1,
        "08:30":2,
        "08:45":3,
        "09:00":4,
        "09:15":5,
        "09:30":6,
        "09:45":7,
        "10:00":8,
        "10:15":9,
        "10:30":10,
        "10:45":11,
        "11:00":12,
        "11:15":13,
        "11:30":14,
        "11:45":15,
      };













export const TimetableViewRows = [
    'xxsmall', 
    'xxsmall', 
    'xxsmall',
    'xxsmall', 
    'xxsmall', 
    'xxsmall',
    'xxsmall', 
    'xxsmall', 
    'xxsmall',
    'xxsmall', 
    'xxsmall', 
    'xxsmall',
    'xxsmall', 
    'xxsmall', 
    'xxsmall',
    'xxsmall', 
    'xxsmall', 
    'xxsmall',
    'xxsmall', 
    'xxsmall', 
    'xxsmall',
    'xxsmall', 
    'xxsmall', 
    'xxsmall',
    'xxsmall', 
    'xxsmall', 
    'xxsmall',
    'xxsmall', 
    'xxsmall', 
    'xxsmall',
    'xxsmall', 
    'xxsmall', 
    'xxsmall',
    'xxsmall', 
    'xxsmall', 
    'xxsmall',
    'xxsmall', 
    'xxsmall', 
    'xxsmall',
    'xxsmall', 
    'xxsmall', 
    'xxsmall',
    'xxsmall', 
    'xxsmall', 
    'xxsmall',
    'xxsmall', 
    'xxsmall', 
    'xxsmall',
    'xxsmall', 
    'xxsmall', 
    'xxsmall', 
    'xxsmall', 
    'xxsmall', 
    'xxsmall', 
    'xxsmall'
]







